// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import PageController from "./page_controller";
import SearchController from "./search_controller";
import PdfUploadController from "./pdf_upload_controller";
application.register("page", PageController);
application.register("search", SearchController);
application.register("pdf-upload", PdfUploadController);
